---
name: Continuous Integration

on:
  push:
    branches:
      - "**"
      - "!production"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "done"
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: "14"
      # - run: yarn install
      # - run: yarn test
