name: Continuous Deployment

# Run on each commit pushed to the production branch
on:
  push:
    branches:
      - production

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Testing...'
  deploy:
    name: Deploy to production server
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Deploying...'
      - run: pwd
      - run: ls -la
      - run: whoami
      - run: scp remote/install.sh jw@server.floatplane.dev/var/www/floatplane.dev
      - run: ssh jw@server.floatplane.dev "/var/www/floatplane.dev/install.sh production xxx"
