name: Continuous Deployment

# Only run on the production branch
on:
  push:
    branches:
      - production

# Use the Docker image found in the root
runs:
  using: "docker"
  image: "Dockerfile"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "production"
      - run: ls -la
      - run: pwd
      - run: nvm install
      - run: nvm install
      - run: yarn install
      - run: yarn test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "production"
      - run: ls -la
      - run: pwd
      - run: scp remote/install.sh jw@server.floatplane.dev/var/www/floatplane.dev
      - run: ssh jw@server.floatplane.dev "/var/www/floatplane.dev/install.sh production xxx"
