name: Continuous Deployment

on:
  push:
    branches:
      - production

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "production"
      - uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"
      - run: node -v
      - run: yarn -v
      - run: yarn install
      - run: yarn test
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "production"
      - uses: alinz/ssh-scp-action@master
        env:
          HELLO: cool
          MESSAGE: hello world
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          # runs this on remove server
          ssh_before: |
            echo $HELLO
            echo $MESSAGE
            ls -lath
          # then uploads these 2 files
          scp: |
            remote/install.sh jw@server.floatplane.dev:/var/www/floatplane.dev
          # then run these commands
          ssh_after: |
            echo $HELLO
            echo $MESSAGE
            ls -lath
            /var/www/floatplane.dev/install.sh production xxx
          # - run: scp remote/install.sh jw@server.floatplane.dev:/var/www/floatplane.dev
          # - run: ssh jw@server.floatplane.dev "/var/www/floatplane.dev/install.sh production xxx"
