name: Continuous Integration

# Run on each commit pushed to any branch, except production
on:
  push:
    branches:
      - master
      - "feature/**"
      - "enhance/**"
      - "fix/**"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Testing...'
